CREATE TABLE zonas_acceso (
    id_zona INT AUTO_INCREMENT,
    cod_zona VARCHAR(6) NOT NULL,
    nom_zona VARCHAR(100) NOT NULL,
    PRIMARY KEY (cod_zona),
    UNIQUE KEY (id_zona)
);

INSERT INTO zonas_acceso(cod_zona, nom_zona)
      select cod_zona="", nom_zona="""
union select cod_zona=" ", nom_zona="MOSTRAR""
union select cod_zona="082", nom_zona=" San Javier"
union select cod_zona="076", nom_zona=" Vicuña"
union select cod_zona="071", nom_zona="Ancud"
union select cod_zona="017", nom_zona="Antofagasta"
union select cod_zona="040", nom_zona="Arauco"
union select cod_zona="004", nom_zona="Arica"
union select cod_zona="039", nom_zona="CASTRO"
union select cod_zona="049", nom_zona="Calama"
union select cod_zona="008", nom_zona="Calera"
union select cod_zona="056", nom_zona="Cauquenes"
union select cod_zona="066", nom_zona="Chanco"
union select cod_zona="019", nom_zona="Chiguayante"
union select cod_zona="005", nom_zona="Chillán"
union select cod_zona="055", nom_zona="Chiloe"
union select cod_zona="020", nom_zona="Chimbarongo"
union select cod_zona="057", nom_zona="Collipulli"
union select cod_zona="021", nom_zona="Coltauco"
union select cod_zona="012", nom_zona="Concepción"
union select cod_zona="006", nom_zona="Copiapó"
union select cod_zona="022", nom_zona="Coquimbo"
union select cod_zona="045", nom_zona="Coyhaique"
union select cod_zona="023", nom_zona="Curacaví"
union select cod_zona="007", nom_zona="Curicó"
union select cod_zona="024", nom_zona="Dalcahue"
union select cod_zona="025", nom_zona="El Tabo"
union select cod_zona="026", nom_zona="Fresia"
union select cod_zona="074", nom_zona="Frutillar"
union select cod_zona="009", nom_zona="Iquique"
union select cod_zona="068", nom_zona="La Ligua"
union select cod_zona="077", nom_zona="La Serena"
union select cod_zona="011", nom_zona="La Unión"
union select cod_zona="075", nom_zona="Laja"
union select cod_zona="058", nom_zona="Lanco"
union select cod_zona="069", nom_zona="Lautaro"
union select cod_zona="080", nom_zona="Licantén"
union select cod_zona="015", nom_zona="Linares"
union select cod_zona="018", nom_zona="Litoral"
union select cod_zona="044", nom_zona="Llanquihue"
union select cod_zona="053", nom_zona="Los Andes"
union select cod_zona="041", nom_zona="Los Angeles"
union select cod_zona="079", nom_zona="Metropolitana"
union select cod_zona="047", nom_zona="Metropolitana Norte"
union select cod_zona="042", nom_zona="Metropolitana Sur"
union select cod_zona="050", nom_zona="Molina"
union select cod_zona="028", nom_zona="Mostazal"
union select cod_zona="052", nom_zona="Nacimiento"
union select cod_zona="072", nom_zona="Natales"
union select cod_zona="054", nom_zona="Negrete"
union select cod_zona="010", nom_zona="Osorno"
union select cod_zona="027", nom_zona="Ovalle"
union select cod_zona="081", nom_zona="Parral"
union select cod_zona="067", nom_zona="Peralillo"
union select cod_zona="029", nom_zona="Pichilemu"
union select cod_zona="013", nom_zona="Pitrufquén"
union select cod_zona="062", nom_zona="Puchuncaví"
union select cod_zona="078", nom_zona="Pucón"
union select cod_zona="002", nom_zona="Puerto Montt"
union select cod_zona="035", nom_zona="Punta Arenas"
union select cod_zona="051", nom_zona="Quillota"
union select cod_zona="037", nom_zona="Quillón"
union select cod_zona="038", nom_zona="Quillón-Chillan"
union select cod_zona="048", nom_zona="Quilpué"
union select cod_zona="059", nom_zona="Quintero"
union select cod_zona="065", nom_zona="Quirihue"
union select cod_zona="043", nom_zona="RANCAGUA"
union select cod_zona="064", nom_zona="Salamanca"
union select cod_zona="003", nom_zona="San Felipe"
union select cod_zona="030", nom_zona="San Fernando"
union select cod_zona="031", nom_zona="San Vicente"
union select cod_zona="032", nom_zona="Santa Cruz"
union select cod_zona="070", nom_zona="Talagante"
union select cod_zona="061", nom_zona="Talca"
union select cod_zona="060", nom_zona="Temuco"
union select cod_zona="033", nom_zona="Teodoro Schmidt"
union select cod_zona="046", nom_zona="Traiguén"
union select cod_zona="001", nom_zona="V Región"
union select cod_zona="014", nom_zona="VI Región"
union select cod_zona="063", nom_zona="Valdivia"
union select cod_zona="073", nom_zona="Vallenar"
union select cod_zona="034", nom_zona="Villarrica"
union select cod_zona="016", nom_zona="Viña del Mar"
union select cod_zona="036", nom_zona="Chimbarongo - San Fernando"