[package]
name = "backend-rust2"
version = "0.1.0"
edition = "2025"
author = "ivitta"

[dependencies]
actix-web = "4"
mysql_async = "0.32"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"
